{
   'name': 'FIS Integration',
    'version': '0.9',
    'category': 'Generic Modules',
    'description': """\
            """,
    'author': 'Emile van Sebille',
    'maintainer': 'Emile van Sebille',
    'website': 'www.openerp.com',
    'depends': [
            "base",
            "auth_signup",
            "crm",
            "fleet_hr",
            "fnx",
            "fnx_fs",
            "hr",
            "hr_insurance",
            "hr_training",
            "hr_workers_comp",
            "product",
            "project",
            "sample",
            "wiki",
            ],
    'data': [
            'account_view.xaml',
            'hr_employee_view.xaml',
            'res_config_view.xaml',
            'res_partner_view.xaml',
            'res_partner_data.xaml',
            'res_users_view.xaml',
            'product_data.xaml',
            'product_view.xaml',
            'project_view.xaml',
            'crm_lead_view.xaml',
            'security/fis_security.xaml',
            'security/ir.model.access.csv',
            'wizard/merge_view.xaml',
            ],
    'css': [
            'static/src/css/fis.css',
            ],
    'js': [
            'static/src/js/fis.js',
            ],
    'test': [],
    'installable': True,
    'active': False,
}
