#!/usr/local/bin/suid-python
"""
This script is designed to:

    - lock up if the labeltime connection is hosed
    - abort subsequent runs if previous locked-up run exists

The product image display routines will look for this script's PID file,
and use the cached versions if it is present.

This scripts is meant to run at least every five minutes.
"""

from __future__ import print_function
from scription import *
from antipathy import Path
from datetime import timedelta
from fnx_script_support import Notify
from pandaemonium import PidLockFile, AlreadyLocked

PID_FILE = Path('/opt/openerp/var/run/test_mnt_labeltime.pid')
LLC_FILE = Path('/mnt/labeltime/Labels/LabelLinkCtl')
CUT_OFF = 6

@Command(
        test=('pretend error condition and send mail', FLAG)
        )
def check_labeltime_connection(test):
    errors = []
    #
    try:
        if test:
            errors.append('testing notifications')
        else:
            with PidLockFile(PID_FILE, timeout=1):
                cat = Execute('cat %s' % LLC_FILE)
                print(cat.stdout)
    except AlreadyLocked:
        errors.append('cat of LabelLinkCtl has stalled')
    #
    notify = Notify(
            script_name,
            cut_off=CUT_OFF,
            )
    notify(errors)


Run()
