#!/usr/local/sbin/suid-python
"""\
Update OpenERP tables from FIS source files.

Downloads selected FIS files, determine which have changed, finds the
appropriate script, and runs it.
"""

from __future__ import print_function
from scription import *
from antipathy import Path
from logging import getLogger, INFO, Formatter, handlers
import os
import updates
updates.script_verbosity = script_verbosity


# two directories are used, one for old data and one for the new incoming
# data;

# which is used is determined by the timestamp on a specifec file
# called age


@Script()
def main():
    print('getting logger', verbose=2)
    global logger, master, path, pre, old, new, active_files, config
    logger = getLogger()
    logger.setLevel(INFO)
    _handler = handlers.RotatingFileHandler(
            '/var/log/openerp/update_fis.log',
            maxBytes=1024*1024*1024,
            backupCount=30,
            )
    _formatter = Formatter('%(process)06d %(asctime)s %(name)-25s %(message)s')
    _handler.setFormatter(_formatter)
    logger.addHandler(_handler)
    config = OrmFile('%s/config/fnx.ini' % os.environ['VIRTUAL_ENV'], types={'_path':Path})
    master = config.network.fis_data_host
    path = config.network.fis_data_path
    pre = config.network.fis_data_prefix
    old = config.network.fis_data_local_old_path
    new = config.network.fis_data_local_path
    active_files = config.network.fis_openerp_files.split()

@Command(
        method=Spec(
            'perform quick or full comparison [quick: compare against old FIS files;'
            ' full: compare against OpenERP records',
            choices=['quick', 'full'],
            default='quick',
            type=lambda f: f.lower(),
            ),

        skip_copy=Spec('Skip copying files', FLAG),
        dryrun=Spec('do not actually make changes', FLAG),
        list_records=Spec('list affected records', FLAG),
        )
def fis_update(method, skip_copy, dryrun, list_records):
    """
    update FIS files from master, then FIS data in OpenERP

    copy from network.fis_data_local_path to network.fis_data_local_old_path
    copy from network.fis_data_host/path to network.fis_data_local_path
    calculate changed files
    find update scripts for those files
    run scripts
    """
    #
    # step 1: move files around
    #
    if not skip_copy:
        print('copying files')
        # copy files to old path
        system('rsync -a %s/ %s' % (new, old))
        # calculate which files to grab from master
        if method == 'full':
            files = '{path}/{pre}???? {path}/{pre}????? {path}/{pre}??????'.format(path=path, pre=pre).split()
        else:
            files = ['%s/%s%s' % (path, pre, f) for f in active_files]
        # and grab them
        system('rsync --bwlimit=10 %s:%s %s/' % (master, ' :'.join(files), new))
    system('chown -R openerp: /FIS')
    config.network.fis_data_local_path.chmod(0o440, '*')
    #
    # step 2: determine which files changed
    #
    print('checking for changed files')
    files = [
        f for f in new.glob('O????') if
            f.stat().st_mtime != old.stat(f.filename).st_mtime
        ]
    files.extend([
        f for f in new.glob('O?????') if
            f.stat().st_mtime != old.stat(f.filename).st_mtime
        ])
    files.extend([
        f for f in new.glob('O??????') if
            f.stat().st_mtime != old.stat(f.filename).st_mtime
        ])
    # strip path and leading {pre} from filenames
    files = [f.filename[1:] for f in files]
    print('changed files: %s [%s]' % (len(files), ', '.join(files)), verbose=1)
    #
    # step 3: get appropriate scripts, and execute them
    #
    FIS_mapping = updates.get_script_mapping()
    for script, tables in FIS_mapping.items():
        cmd = '/opt/bin/updates/%s %s --method=%s' % (script, ','.join(tables), method)
        if dryrun:
            cmd += ' --dryrun'
        if list_records:
            cmd += ' --list-records'
        if script_verbosity:
            cmd += ' -' + 'v' * script_verbosity
        system(cmd)


def system(cmd, on_error='abort'):
    with user_ids(0, 0):
        print('--== running "%s" . . .: ' % cmd, end='', verbose=1)
        job = Execute(cmd, pty=True)
        print(job.returncode, '==--', verbose=1)
        if job.returncode or job.stderr:
            # unable to copy files -- abort
            error('Error with command (returncode %r):' % (job.returncode, ))
            error('------------------ cmd  ------------------')
            error(cmd)
            if job.stdout.strip():
                error('----------------- stdout -----------------')
                error(job.stdout.strip())
            error('----------------- stderr -----------------')
            if job.stderr.strip():
                error(job.stderr.strip())
                error('==========================================')
            if on_error == 'abort':
                abort()
        elif job.stdout.strip():
            print('---- stdout ----', verbose=1)
            print(job.stdout.strip(), verbose=1)
            print('=' * 25, verbose=1)

Main()
